// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpctest.proto

package com.soeasycode.demo;

public interface TestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:onlytest.TestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
